version: '3.8'

services:
    gpt4:
      build:
        context: .
	dockerfile: Dockerfile
	image: gpt4free:latest
      container_name: gpt4
      ports: 
        - 8501:8501
      restart: unless-stopped
      read_only: true
		
