version: '3'

services:
  gpt4free:
    image: ghcr.io/xtekky/gpt4free:latest
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - '8080:80'
      - '1337:1337'
      - '7900:7900'