version: "3.9"

services:
  gpt4free:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dc_gpt4free
    environment:
      - http_proxy=http://127.0.0.1:1080
      - https_proxy=http://127.0.0.1:1080
    image: img_gpt4free
    ports:
      - 8501:8501
    restart: always